/*
INSERT INTO TB_ROLE(NAME) VALUES('ADMIN');
INSERT INTO TB_ROLE(NAME) VALUES('USER');
INSERT INTO TB_USER(USERNAME, PASSWORD) VALUES('admin', 'admin');
INSERT INTO TB_USER(USERNAME, PASSWORD) VALUES('user', 'user');
INSERT INTO TB_USER_ROLE(USER_ID, ROLE_ID) VALUES(1, 1);
INSERT INTO TB_USER_ROLE(USER_ID, ROLE_ID) VALUES(2, 2);
*/